[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['cd backend && npm run build']

[start]
cmd = 'cd backend && node dist/index.js'
