[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && node dist/index.js"
healthcheckPath = "/api/rewards"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nixPkgs = ["nodejs_18", "npm"]
